import type { LocalizationResource } from '@clerk/types';

export const slSL: LocalizationResource = {
  locale: 'sl-SL',
  apiKeys: {
    action__add: 'Add new key',
    action__search: 'Search keys',
    createdAndExpirationStatus__expiresOn:
      "Ustvarjeno {{ createdDate | shortDate('en-US') }} • Poteče {{ expiresDate | longDate('en-US') }}",
    createdAndExpirationStatus__never: "Ustvarjeno {{ createdDate | shortDate('en-US') }} • Poteče nikoli",
    detailsTitle__emptyRow: 'Ni najdenih API ključev',
    formButtonPrimary__add: 'Ustvari ključ',
    formFieldCaption__expiration__expiresOn: 'Poteče {{ date }}',
    formFieldCaption__expiration__never: 'Ta ključ ne bo potekel',
    formFieldOption__expiration__180d: '180 dni',
    formFieldOption__expiration__1d: '1 dan',
    formFieldOption__expiration__1y: '1 leto',
    formFieldOption__expiration__30d: '30 dni',
    formFieldOption__expiration__60d: '60 dni',
    formFieldOption__expiration__7d: '7 dni',
    formFieldOption__expiration__90d: '90 dni',
    formFieldOption__expiration__never: 'Nikoli',
    formHint: 'Vpišite ime za ustvarjanje novega ključa. Ključ lahko prekličete kadarkoli.',
    formTitle: 'Ustvari novi API ključ',
    lastUsed__days: 'pred {{days}} dnevi',
    lastUsed__hours: 'pred {{hours}} urami',
    lastUsed__minutes: 'pred {{minutes}} minutami',
    lastUsed__months: 'pred {{months}} meseci',
    lastUsed__seconds: 'pred {{seconds}} sekundami',
    lastUsed__years: 'pred {{years}} leti',
    menuAction__revoke: 'Prekliči ključ',
    revokeConfirmation: {
      confirmationText: 'Prekliči',
      formButtonPrimary__revoke: 'Prekliči ključ',
      formHint: 'Ali ste prepričani, da želite izbrisati ta varnostni ključ?',
      formTitle: 'Prekliči "{{apiKeyName}}" varnostni ključ?',
    },
  },
  backButton: 'Nazaj',
  badge__activePlan: 'Aktivno',
  badge__canceledEndsAt: "Preklicano • Poteče {{ date | shortDate('en-US') }}",
  badge__currentPlan: 'Trenutni način',
  badge__default: 'Privzeto',
  badge__endsAt: "Poteče {{ date | shortDate('en-US') }}",
  badge__expired: 'Pretečeno',
  badge__otherImpersonatorDevice: 'Drugo nadomestno napravo',
  badge__pastDueAt: "Preteče {{ date | shortDate('en-US') }}",
  badge__pastDuePlan: 'Preteče',
  badge__primary: 'Glavno',
  badge__renewsAt: "Se obnovi {{ date | shortDate('en-US') }}",
  badge__requiresAction: 'Zahteva dejanje',
  badge__startsAt: "Začne {{ date | shortDate('en-US') }}",
  badge__thisDevice: 'Ta naprava',
  badge__unverified: 'Ni potrjeno',
  badge__upcomingPlan: 'Prihajajoči način',
  badge__userDevice: 'Uporabniška naprava',
  badge__you: 'Ti',
  commerce: {
    addPaymentMethod: 'Dodaj način plačila',
    alwaysFree: 'Vedno brezplačno',
    annually: 'Letno',
    availableFeatures: 'Dostopne funkcije',
    billedAnnually: 'Zaračunano letno',
    billedMonthlyOnly: 'Izključno zaračunano mesečno',
    cancelSubscription: 'Prekliči naročnino',
    cancelSubscriptionAccessUntil:
      "Vse funkcije '{{plan}}' lahko uporabljate do {{ date | longDate('en-US') }}, nato ne boste imeli več dostopa.",
    cancelSubscriptionNoCharge: 'Za to naročnino ne boste obračunani.',
    cancelSubscriptionTitle: 'Prekliči naročnino {{plan}}?',
    cannotSubscribeMonthly:
      'Za to naročnino ne morete plačati mesečno. Za to naročnino morate izbrati plačilo letno.',
    cannotSubscribeUnrecoverable:
      'Za to naročnino ne morete naročiti. Vaša trenutna naročnina je dražja od tega naročnina.',
    checkout: {
      description__paymentSuccessful: 'Vaše plačilo je uspešno.',
      description__subscriptionSuccessful: 'Vaša nova naročnina je pripravljena.',
      downgradeNotice:
        'Vaša trenutna naročnina in njene funkcije boste ohranjene do konca obračunskega cikla, nato pa boste preklopili na to naročnino.',
      emailForm: {
        subtitle: 'Preden lahko dokončate svojo nakup, morate dodati e-poštni naslov, na katerega bodo poslane računi.',
        title: 'Dodaj e-poštni naslov',
      },
      lineItems: {
        title__paymentMethod: 'Način plačila',
        title__statementId: 'ID računa',
        title__subscriptionBegins: 'Naročnina začne',
        title__totalPaid: 'Skupaj plačano',
      },
      pastDueNotice: 'Vaša prejšnja naročnina je pretečena, brez plačila.',
      perMonth: 'na mesec',
      title: 'Nakup',
      title__paymentSuccessful: 'Plačilo je uspešno!',
      title__subscriptionSuccessful: 'Uspešno!',
    },
    credit: 'Dobropis',
    creditRemainder: 'Dobropis za preostanek vaše trenutne naročnine',
    defaultFreePlanActive: "Trenutno ste na brezplačnem načinu",
    free: 'Brezplačno',
    getStarted: 'Začnite',
    keepSubscription: 'Nadaljujte naročnino',
    manage: 'Upravljaj',
    manageSubscription: 'Upravljaj naročnino',
    month: 'Mesec',
    monthly: 'Mesečno',
    pastDue: 'Preteče',
    pay: 'Plačaj {{amount}}',
    paymentMethods: 'Načini plačila',
    paymentSource: {
      applePayDescription: {
        annual: 'Letno plačilo',
        monthly: 'Mesečno plačilo',
      },
      dev: {
        anyNumbers: 'Katerakoli številka',
        cardNumber: 'Številka kartice',
        cvcZip: 'CVC, ZIP',
        developmentMode: 'Razvojni način',
        expirationDate: 'Datum poteka',
        testCardInfo: 'Podatki testne kartice',
      },
    },
    popular: 'Popular',
    pricingTable: {
      billingCycle: 'Obračunski cikel',
      included: 'Vključeno',
    },
    reSubscribe: 'Ponovno naroči',
    seeAllFeatures: 'Oglejte si vse funkcije',
    subscribe: 'Naroči',
    subscriptionDetails: {
      beginsOn: 'Začne',
      currentBillingCycle: 'Trenutni obračunski cikel',
      endsOn: 'Poteče',
      nextPaymentAmount: 'Naslednje plačilo',
      nextPaymentOn: 'Naslednje plačilo',
      pastDueAt: 'Preteče',
      renewsAt: 'Se obnovi',
      subscribedOn: 'Naročen',
      title: 'Naročnina',
    },
    subtotal: 'Skupaj',
    switchPlan: 'Preklopi na to način',
    switchToAnnual: 'Preklopi na letno',
    switchToAnnualWithAnnualPrice: 'Preklopi na letno {{currency}}{{price}} / leto',
    switchToMonthly: 'Preklopi na mesečno',
    switchToMonthlyWithPrice: 'Preklopi na mesečno {{currency}}{{price}} / mesec',
    totalDue: 'Skupaj za plačilo',
    totalDueToday: 'Skupaj za plačilo danes',
    viewFeatures: 'Oglejte si funkcije',
    viewPayment: 'Oglejte si plačilo',
    year: 'Leto',
  },
  createOrganization: {
    formButtonSubmit: 'Ustvari organizacijo',
    invitePage: {
      formButtonReset: 'Preskoči',
    },
    title: 'Ustvari organizacijo',
  },
  dates: {
    lastDay: "Včeraj ob {{ date | timeString('en-US') }}",
    next6Days: "{{ date | weekday('en-US','long') }} ob {{ date | timeString('en-US') }}",
    nextDay: "Jutri ob {{ date | timeString('en-US') }}",
    numeric: "{{ date | numeric('en-US') }}",
    previous6Days: "{{ date | weekday('en-US','long') }} ob {{ date | timeString('en-US') }}",
    sameDay: "Danes ob {{ date | timeString('en-US') }}",
  },
  dividerText: 'ali',
  footerActionLink__alternativePhoneCodeProvider: 'Pošlji kodo prek SMS namesto e-pošte',
  footerActionLink__useAnotherMethod: 'Uporabi drugo metodo',
  footerPageLink__help: 'Pomoč',
  footerPageLink__privacy: 'Zasebnost',
  footerPageLink__terms: 'Pogoji',
  formButtonPrimary: 'Nadaljuj',
  formButtonPrimary__verify: 'Potrdi',
  formFieldAction__forgotPassword: 'Pozabljeno geslo?',
  formFieldError__matchingPasswords: 'Gesli se ujemata.',
  formFieldError__notMatchingPasswords: "Gesli se ne ujemata.",
  formFieldError__verificationLinkExpired: 'Povezava za potrditev je potekla. Zahtevajte novo povezavo.',
  formFieldHintText__optional: 'Neobvezno',
  formFieldHintText__slug: 'Slug je čitljiv ID, ki mora biti edinstven. Pogosto se uporablja v URL-jih.',
  formFieldInputPlaceholder__apiKeyDescription: 'Pojasnite, zakaj generirate ta ključ',
  formFieldInputPlaceholder__apiKeyExpirationDate: 'Izberi datum',
  formFieldInputPlaceholder__apiKeyName: 'Vpišite ime skrivnega ključa',
  formFieldInputPlaceholder__backupCode: 'Vpišite kodo za varnostno kopijo',
  formFieldInputPlaceholder__confirmDeletionUserAccount: 'Izbriši račun',
  formFieldInputPlaceholder__emailAddress: 'Vpišite svoj e-poštni naslov',
  formFieldInputPlaceholder__emailAddress_username: 'Vpišite e-poštni naslov ali uporabniško ime',
  formFieldInputPlaceholder__emailAddresses: 'example@email.com, example2@email.com',
  formFieldInputPlaceholder__firstName: 'Ime',
  formFieldInputPlaceholder__lastName: 'Priimek',
  formFieldInputPlaceholder__organizationDomain: 'example.com',
  formFieldInputPlaceholder__organizationDomainEmailAddress: 'you@example.com',
  formFieldInputPlaceholder__organizationName: 'Ime organizacije',
  formFieldInputPlaceholder__organizationSlug: 'my-org',
  formFieldInputPlaceholder__password: 'Vpišite svoje geslo',
  formFieldInputPlaceholder__phoneNumber: 'Vpišite svoj telefonski naslov',
  formFieldInputPlaceholder__username: undefined,
  formFieldLabel__apiKeyDescription: 'Opis',
  formFieldLabel__apiKeyExpiration: 'Potek',
  formFieldLabel__apiKeyName: 'Ime skrivnega ključa',
  formFieldLabel__automaticInvitations: 'Omogoči samodejne pozivnice za to domeno',
  formFieldLabel__backupCode: 'Koda za varnostno kopijo',
  formFieldLabel__confirmDeletion: 'Potrditev',
  formFieldLabel__confirmPassword: 'Potrdite geslo',
  formFieldLabel__currentPassword: 'Trenutno geslo',
  formFieldLabel__emailAddress: 'E-poštni naslov',
  formFieldLabel__emailAddress_username: 'E-poštni naslov ali uporabniško ime',
  formFieldLabel__emailAddresses: 'E-poštni naslovi',
  formFieldLabel__firstName: 'Ime',
  formFieldLabel__lastName: 'Priimek',
  formFieldLabel__newPassword: 'Novo geslo',
  formFieldLabel__organizationDomain: 'Domena',
  formFieldLabel__organizationDomainDeletePending: 'Izbriši pozivnice in predloge',
  formFieldLabel__organizationDomainEmailAddress: 'E-poštni naslov za potrditev',
  formFieldLabel__organizationDomainEmailAddressDescription:
    'Vpišite e-poštni naslov pod to domeno, da prejmete kodo in potrdite to domeno.',
  formFieldLabel__organizationName: 'Ime',
  formFieldLabel__organizationSlug: 'Slug',
  formFieldLabel__passkeyName: 'Ime ključa',
  formFieldLabel__password: 'Geslo',
  formFieldLabel__phoneNumber: 'Telefonski naslov',
  formFieldLabel__role: 'Vloga',
  formFieldLabel__signOutOfOtherSessions: 'Odjavi se z vseh naprav',
  formFieldLabel__username: 'Uporabniško ime',
  impersonationFab: {
    action__signOut: 'Odjavi se',
    title: 'Prijavljen kot {{identifier}}',
  },
  maintenanceMode:
"Trenutno potekajo vzdrževalna dela, vendar brez skrbi, ne bi smelo trajati več kot nekaj minut.",
  membershipRole__admin: 'Admin',
  membershipRole__basicMember: 'Član',
  membershipRole__guestMember: 'Gost',
  organizationList: {
    action__createOrganization: 'Ustvari organizacijo',
    action__invitationAccept: 'Pridruži se',
    action__suggestionsAccept: 'Zahtevaj pridružitev',
    createOrganization: 'Ustvari organizacijo',
    invitationAcceptedLabel: 'Pridružen',
    subtitle: 'da nadaljujete na {{applicationName}}',
    suggestionsAcceptedLabel: 'Čakajoča odobritev',
    title: 'Izberite račun',
    titleWithoutPersonal: 'Izberite organizacijo',
  },
  organizationProfile: {
    apiKeysPage: {
      title: 'API ključi',
    },
    badge__automaticInvitation: 'Samodejne pozivnice',
    badge__automaticSuggestion: 'Samodejne predloge',
    badge__manualInvitation: 'Ni samodejne prijave',
    badge__unverified: 'Ni potrjeno',
    billingPage: {
      paymentHistorySection: {
        empty: 'Ni zgodovine plačil',
        notFound: 'Najdena ni',
        tableHeader__amount: 'Znesek',
        tableHeader__date: 'Datum',
        tableHeader__status: 'Status',
      },
      paymentSourcesSection: {
        actionLabel__default: 'Nastavi kot privzeto',
        actionLabel__remove: 'Odstrani',
        add: 'Dodaj novi način plačila',
        addSubtitle: 'Dodaj novi način plačila na svoj račun.',
        cancelButton: 'Prekliči',
        formButtonPrimary__add: 'Dodaj način plačila',
        formButtonPrimary__pay: 'Plačaj {{amount}}',
        payWithTestCardButton: 'Plačaj z testno kartico',
        removeResource: {
          messageLine1: '{{identifier}} bo odstranjen iz tega računa.',
          messageLine2:
'Tega plačilnega vira ne boste mogli več uporabljati in vse ponavljajoče se naročnine, ki so od njega odvisne, ne bodo več delovale.',
          successMessage: '{{paymentSource}} je bil odstranjen iz vašega računa.',
          title: 'Odstrani način plačila',
        },
        title: 'Načini plačila',
      },
      start: {
        headerTitle__payments: 'Plačila',
        headerTitle__plans: 'Načini',
        headerTitle__statements: 'Računi',
        headerTitle__subscriptions: 'Naročnina',
      },
      statementsSection: {
        empty: 'Ni računov za prikaz',
        itemCaption__paidForPlan: 'Plačano za {{plan}} {{period}} način',
        itemCaption__proratedCredit: 'Proratirana dobropis za delno uporabo prejšnje naročnine',
        itemCaption__subscribedAndPaidForPlan: 'Naročen in plačan za {{plan}} {{period}} način',
        notFound: 'Račun ni najden',
        tableHeader__amount: 'Znesek',
        tableHeader__date: 'Datum',
        title: 'Računi',
        totalPaid: 'Skupaj plačano',
      },
      subscriptionsListSection: {
        actionLabel__newSubscription: 'Naroči se na način',
        actionLabel__switchPlan: 'Preklopi načine',
        tableHeader__edit: 'Uredi',
        tableHeader__plan: 'Način',
        tableHeader__startDate: 'Začetek',
        title: 'Naročnina',
      },
      subscriptionsSection: {
        actionLabel__default: 'Upravljaj',
      },
      switchPlansSection: {
        title: 'Preklopi načine',
      },
      title: 'Računovodstvo',
    },
    createDomainPage: {
      subtitle:
'Dodajte domeno za preverjanje. Uporabniki z e-poštnimi naslovi v tej domeni se lahko organizaciji pridružijo samodejno ali pa zaprosijo za pridružitev.',
      title: 'Dodaj domeno',
    },
    invitePage: {
      detailsTitle__inviteFailed:
'Povabil ni bilo mogoče poslati. Za naslednje e-poštne naslove že obstajajo čakajoča povabila: {{email_addresses}}.',
      formButtonPrimary__continue: 'Pošlji povabila',
      selectDropdown__role: 'Izberi vlogo',
      subtitle: 'Vpišite ali prilepite enega ali več e-poštnih naslovov, ločenih z presledki ali vejicami.',
      successMessage: 'Povabila so uspešno poslana',
      title: 'Povabi nove člane',
    },
    membersPage: {
      action__invite: 'Povabi',
      action__search: 'Poišči',
      activeMembersTab: {
        menuAction__remove: 'Odstrani člana',
        tableHeader__actions: 'Dejanja',
        tableHeader__joined: 'Pridružen',
        tableHeader__role: 'Vloga',
        tableHeader__user: 'Uporabnik',
      },
      detailsTitle__emptyRow: 'Ni članov za prikaz',
      invitationsTab: {
        autoInvitations: {
          headerSubtitle:
'Povabite uporabnike tako, da povežete e-poštno domeno z vašo organizacijo. Vsak, ki se prijavi z ustrezno e-poštno domeno, se bo lahko kadar koli pridružil organizaciji.',
          headerTitle: 'Samodejne povabila',
          primaryButton: 'Upravljaj potrjene domene',
        },
        table__emptyRow: 'Ni povabila za prikaz',
      },
      invitedMembersTab: {
        menuAction__revoke: 'Prekliči povabilo',
        tableHeader__invited: 'Povabljeni',
      },
      requestsTab: {
        autoSuggestions: {
          headerSubtitle:
          'Uporabniki, ki se prijavijo z ujemajočo se e-poštno domeno, bodo lahko videli predlog za zahtevo za pridružitev vaši organizaciji.',
          headerTitle: 'Samodejne predloge',
          primaryButton: 'Upravljaj potrjene domene',
        },
        menuAction__approve: 'Odobri',
        menuAction__reject: 'Zavrni',
        tableHeader__requested: 'Zahtevano dostop',
        table__emptyRow: 'Ni zahtev za prikaz',
      },
      start: {
        headerTitle__invitations: 'Povabila',
        headerTitle__members: 'Člani',
        headerTitle__requests: 'Zahteve',
      },
    },
    navbar: {
      apiKeys: 'API ključi',
      billing: 'Računovodstvo',
      description: 'Upravljajte svojo organizacijo.',
      general: 'Splošno',
      members: 'Člani',
      title: 'Organizacija',
    },
    plansPage: {
      alerts: {
        noPermissionsToManageBilling: 'Nimate dovoljenja za upravljanje računovodstva za to organizacijo.',
      },
      title: 'Načini',
    },
    profilePage: {
      dangerSection: {
        deleteOrganization: {
          actionDescription: 'Vpišite "{{organizationName}}" spodaj, da nadaljujete.',
          messageLine1: 'Ali ste prepričani, da želite izbrisati to organizacijo?',
          messageLine2: 'To dejanje je trajno in nepovratno.',
          successMessage: 'Organizacija je bila izbrisana.',
          title: 'Izbriši organizacijo',
        },
        leaveOrganization: {
          actionDescription: 'Vpišite "{{organizationName}}" spodaj, da nadaljujete.',
          messageLine1:
            'Ali ste prepričani, da želite zapustiti to organizacijo? Izgubite dostop do te organizacije in njenih aplikacij.',
          messageLine2: 'To dejanje je trajno in nepovratno.',
          successMessage: 'Organizacija je bila zapuščena.',
          title: 'Zapusti organizacijo',
        },
        title: 'Nevarno',
      },
      domainSection: {
        menuAction__manage: 'Upravljaj',
        menuAction__remove: 'Odstrani',
        menuAction__verify: 'Potrdi',
        primaryButton: 'Dodaj domeno',
        subtitle:
          'Dovolite uporabnikom, da se samodejno ali po zahtevi pridružijo organizaciji na podlagi potrjene e-poštne domene.',
        title: 'Potrjene domene',
      },
      successMessage: 'Organizacija je bila posodobljena.',
      title: 'Posodobi profil',
    },
    removeDomainPage: {
      messageLine1: 'E-poštna domena {{domain}} bo odstranjena.',
      messageLine2: 'Uporabniki ne bodo mogli samodejno pridružiti organizaciji po tem.',
      successMessage: '{{domain}} je bil odstranjen.',
      title: 'Odstrani domeno',
    },
    start: {
      headerTitle__general: 'Splošno',
      headerTitle__members: 'Člani',
      profileSection: {
        primaryButton: 'Posodobi profil',
        title: 'Organizacijski profil',
        uploadAction__title: 'Logo',
      },
    },
    verifiedDomainPage: {
      dangerTab: {
        calloutInfoLabel: 'Odstranitev te domene bo vplivala na povabljene uporabnike.',
        removeDomainActionLabel__remove: 'Odstrani domeno',
        removeDomainSubtitle: 'Odstrani to domeno iz vaših potrjenih domen',
        removeDomainTitle: 'Odstrani domeno',
      },
      enrollmentTab: {
        automaticInvitationOption__description:
          'Uporabniki bodo samodejno povabljeni za pridružitev organizaciji, ko se prijavijo in lahko kadar koli pridružijo.',
        automaticInvitationOption__label: 'Samodejne povabila',
        automaticSuggestionOption__description:
          'Uporabniki prejmejo predlog za zahtevo za pridružitev, vendar morajo biti odobreni z upraviteljem, preden lahko pridružijo organizaciji.',
        automaticSuggestionOption__label: 'Samodejne predloge',
        calloutInfoLabel: 'Sprememba načina pridružitve bo vplivala samo na nove uporabnike.',
        calloutInvitationCountLabel: 'Čakajoča povabila poslana uporabnikom: {{count}}',
        calloutSuggestionCountLabel: 'Čakajoče predloge poslane uporabnikom: {{count}}',
        manualInvitationOption__description: 'Uporabniki lahko samo ročno povabijo v organizacijo.',
        manualInvitationOption__label: 'Ni samodejne pridružitve',
        subtitle: 'Izberite, kako lahko uporabniki z te domene pridružijo organizaciji.',
      },
      start: {
        headerTitle__danger: 'Nevarno',
        headerTitle__enrollment: 'Možnosti pridružitve',
      },
      subtitle: 'Domena {{domain}} je zdaj potrjena. Nadaljujte z izbiro načina pridružitve.',
      title: 'Posodobi {{domain}}',
    },
    verifyDomainPage: {
      formSubtitle: 'Vpišite kodo za preverjanje, ki je bila poslana na vaš e-poštni naslov',
      formTitle: 'Koda za preverjanje',
      resendButton: "Nisi prejel kode? Pošlji ponovno",
      subtitle: 'Domena {{domainName}} mora biti potrjena prek e-pošte.',
      subtitleVerificationCodeScreen: 'Koda za preverjanje je bila poslana na {{emailAddress}}. Vpišite kodo, da nadaljujete.',
      title: 'Potrdi domeno',
    },
  },
  organizationSwitcher: {
    action__createOrganization: 'Ustvari organizacijo',
    action__invitationAccept: 'Pridruži se',
    action__manageOrganization: 'Upravljaj',
    action__suggestionsAccept: 'Zahtevaj pridružitev',
    notSelected: 'Ni izbrane organizacije',
    personalWorkspace: 'Osebni račun',
    suggestionsAcceptedLabel: 'Čakajoča odobritev',
  },
  paginationButton__next: 'Naslednja',
  paginationButton__previous: 'Prejšnja',
  paginationRowText__displaying: 'Prikazanih',
  paginationRowText__of: 'od',
  reverification: {
    alternativeMethods: {
      actionLink: 'Poišči pomoč',
      actionText: 'Nimate nobenega od teh?',
      blockButton__backupCode: 'Uporabi kopijo kode',
      blockButton__emailCode: 'Pošlji kodo na {{identifier}}',
      blockButton__passkey: 'Uporabi svojo ključnico',
      blockButton__password: 'Nadaljuj z vašim geslom',
      blockButton__phoneCode: 'Pošlji SMS kodo na {{identifier}}',
      blockButton__totp: 'Uporabi svojo aplikacijo za preverjanje',
      getHelp: {
        blockButton__emailSupport: 'Pomoč e-pošta',
        content:
        'Če imate težave s preverjanjem računa, nam pišite in pomagali vam bomo, da vam čim prej obnovimo dostop.',
        title: 'Poišči pomoč',
      },
      subtitle: 'Imate težave? Uporabite lahko katerokoli od teh metod za preverjanje.',
      title: 'Uporabi drugo metodo',
    },
    backupCodeMfa: {
      subtitle: 'Vpišite kopijo kode, ki ste jo prejeli pri nastavitvi dvostopenjskega overjanja',
      title: 'Vpišite kopijo kode',
    },
    emailCode: {
      formTitle: 'Koda za preverjanje',
      resendButton: "Nisi prejel kode? Pošlji ponovno",
      subtitle: 'Vpišite kodo, ki je bila poslana na vaš e-poštni naslov, da nadaljujete',
      title: 'Preverjanje je zahtevano',
    },
    noAvailableMethods: {
      message: 'Nimajo nobenih dostopnih metod za preverjanje.',
      subtitle: 'Prišlo je do napake',
      title: 'Nimajo nobenih dostopnih metod za preverjanje.',
    },
    passkey: {
      blockButton__passkey: 'Uporabi svojo kodo',
      subtitle:
        'Uporaba vaše kode potrdi vašo identiteto. Vaše naprave lahko zahtevajo vašo prstni odtis, obraz ali zaklepanje zaslona.',
      title: 'Uporabi svojo kodo',
    },
    password: {
      actionLink: 'Uporabi drugo metodo',
      subtitle: 'Vpišite svoje trenutno geslo, da nadaljujete',
      title: 'Preverjanje je zahtevano',
    },
    phoneCode: {
      formTitle: 'Koda za preverjanje',
      resendButton: "Nisi prejel kode? Pošlji ponovno",
      subtitle: 'Vpišite kodo, ki je bila poslana na vaš telefon, da nadaljujete',
      title: 'Preverjanje je zahtevano',
    },
    phoneCodeMfa: {
      formTitle: 'Koda za preverjanje',
      resendButton: "Niste prejeli kode? Pošlji ponovno",
      subtitle: 'Vpišite kodo, ki je bila poslana na vaš telefon, da nadaljujete',
      title: 'Preverjanje je zahtevano',
    },
    totpMfa: {
      formTitle: 'Koda za preverjanje',
      subtitle: 'Vpišite kodo, ki jo generira vaša aplikacija za preverjanje, da nadaljujete',
      title: 'Preverjanje je zahtevano',
    },
  },
  signIn: {
    accountSwitcher: {
      action__addAccount: 'Dodaj račun',
      action__signOutAll: 'Odjavi vse račune',
      subtitle: 'Izberite račun, s katerim želite nadaljevati.',
      title: 'Izberi račun',
    },
    alternativeMethods: {
      actionLink: 'Poišči pomoč',
      actionText: 'Nimate nobenega od teh?',
      blockButton__backupCode: 'Uporabi kopijo kode',
      blockButton__emailCode: 'Pošlji kodo na {{identifier}}',
      blockButton__emailLink: 'Pošlji povezavo na {{identifier}}',
      blockButton__passkey: 'Prijavi se z vašo kodo',
      blockButton__password: 'Prijavi se z vašim geslom',
      blockButton__phoneCode: 'Pošlji SMS kodo na {{identifier}}',
      blockButton__totp: 'Uporabi svojo aplikacijo za preverjanje',
      getHelp: {
        blockButton__emailSupport: 'Pomoč e-pošta',
        content:
        'Če imate težave s prijavo v račun, nam pišite in pomagali vam bomo, da vam čim prej obnovimo dostop.',
        title: 'Poišči pomoč',
      },
      subtitle: 'Imate težave? Uporabite lahko katerokoli od teh metod za prijavo.',
      title: 'Uporabi drugo metodo',
    },
    alternativePhoneCodeProvider: {
      formTitle: 'Koda za preverjanje',
      resendButton: "Nisi prejel kode? Pošlji ponovno",
      subtitle: 'da nadaljujete do {{applicationName}}',
      title: 'Preverite svoj {{provider}}',
    },
    backupCodeMfa: {
      subtitle: 'Vaša kopija kode je tista, ki ste jo prejeli pri nastavitvi dvostopenjskega overjanja.',
      title: 'Vpišite kopijo kode',
    },
    emailCode: {
      formTitle: 'Koda za preverjanje',
      resendButton: "Nisi prejel kode? Pošlji ponovno",
      subtitle: 'da nadaljujete do {{applicationName}}',
      title: 'Preverite svojo e-pošto',
    },
    emailLink: {
      clientMismatch: {
        subtitle:
        'Za nadaljevanje odprite povezavo za preverjanje v napravi in brskalniku, iz katerega ste sprožili prijavo.',
        title: 'Povezava za preverjanje je neveljavna za to napravo',
      },
      expired: {
        subtitle: 'Vrnite se na izvirni zavihek, da nadaljujete.',
        title: 'Povezava za preverjanje je potekla',
      },
      failed: {
        subtitle: 'Vrnite se na izvirni zavihek, da nadaljujete.',
        title: 'Povezava za preverjanje je neveljavna',
      },
      formSubtitle: 'Uporabite povezavo za preverjanje, ki je bila poslana na vaš e-poštni naslov',
      formTitle: 'Povezava za preverjanje',
      loading: {
        subtitle: 'Boste preusmerjeni čez nekaj sekund',
        title: 'Prijavljeni...',
      },
      resendButton: "Nisi prejel povezave? Pošlji ponovno",
      subtitle: 'da nadaljujete do {{applicationName}}',
      title: 'Preverite svojo e-pošto',
      unusedTab: {
        title: 'Zaprti lahko zavihek',
      },
      verified: {
        subtitle: 'Boste preusmerjeni čez nekaj sekund',
        title: 'Prijavljeni',
      },
      verifiedSwitchTab: {
        subtitle: 'Vrnite se na izvirni zavihek, da nadaljujete.',
        subtitleNewTab: 'Vrnite se na nov odprti zavihek, da nadaljujete.',
        titleNewTab: 'Prijavljeni na drugem zaviheku',
      },
    },
    forgotPassword: {
      formTitle: 'Koda za ponastavitev gesla',
      resendButton: "Nisi prejel kode? Pošlji ponovno",
      subtitle: 'da ponastavite svoje geslo',
      subtitle_email: 'Najprej vpišite kodo, ki je bila poslana na vaš e-poštni naslov',
      subtitle_phone: 'Najprej vpišite kodo, ki je bila poslana na vaš telefon',
      title: 'Ponastavi geslo',
    },
    forgotPasswordAlternativeMethods: {
      blockButton__resetPassword: 'Ponastavi geslo',
      label__alternativeMethods: 'Ali pa se prijavite z drugo metodo',
      title: 'Pozabljeno geslo?',
    },
    noAvailableMethods: {
      message: "Nimajo nobenih dostopnih metod za prijavo.",
      subtitle: 'Prišlo je do napake',
      title: 'Nimajo nobenih dostopnih metod za prijavo.',
    },
    passkey: {
      subtitle: "Uporaba vaše kode potrdi vašo identiteto. Vaše naprave lahko zahtevajo vašo prstni odtis, obraz ali zaklepanje zaslona.",
      title: 'Uporabi svojo kodo',
    },
    password: {
      actionLink: 'Uporabi drugo metodo',
      subtitle: 'Vpišite geslo, povezano z vašim računom',
      title: 'Vpišite geslo',
    },
    passwordPwned: {
      title: 'Geslo je ogroženo',
    },
    phoneCode: {
      formTitle: 'Koda za preverjanje',
      resendButton: "Nisi prejel kode? Pošlji ponovno",
      subtitle: 'da nadaljujete do {{applicationName}}',
      title: 'Preverite svoj telefon',
    },
    phoneCodeMfa: {
      formTitle: 'Koda za preverjanje',
      resendButton: "Nisi prejel kode? Pošlji ponovno",
      subtitle: 'Vpišite kodo, ki je bila poslana na vaš telefon, da nadaljujete',
      title: 'Preverite svoj telefon',
    },
    resetPassword: {
      formButtonPrimary: 'Ponastavi geslo',
      requiredMessage: 'Iz varnostnih razlogov je potrebno ponastaviti geslo.',
      successMessage: 'Vaše geslo je bilo uspešno spremenjeno. Prijavljeni ste, počakajte nekaj sekund.',
      title: 'Nastavi novo geslo',
    },
    resetPasswordMfa: {
      detailsLabel: 'Potrebujemo, da overite vašo identiteto, preden ponastavite geslo.',
    },
    start: {
      actionLink: 'Prijava',
      actionLink__join_waitlist: 'Pridruži se seznamu čakanja',
      actionLink__use_email: 'Uporabi e-pošto',
      actionLink__use_email_username: 'Uporabi e-pošto ali uporabniško ime',
      actionLink__use_passkey: 'Uporabi kodo namesto telefona',
      actionLink__use_phone: 'Uporabi telefon',
      actionLink__use_username: 'Uporabi uporabniško ime',
      actionText: 'Nimate še računa?',
      actionText__join_waitlist: 'Želite zgodnjo dostop?',
      alternativePhoneCodeProvider: {
        actionLink: 'Uporabi drugo metodo',
        label: '{{provider}} telefonska številka',
        subtitle: 'Vpišite svojo telefonsko številko, da dobite kodo za preverjanje na {{provider}}.',
        title: 'Prijavite se na {{applicationName}} z {{provider}}',
      },
      subtitle: 'Pozdravljeni! Prijavite se, da nadaljujete.',
      subtitleCombined: undefined,
      title: 'Prijavite se na {{applicationName}}',
      titleCombined: 'Nadaljujte na {{applicationName}}',
    },
    totpMfa: {
      formTitle: 'Koda za preverjanje',
      subtitle: 'Vpišite kodo, ki jo generira vaša aplikacija za preverjanje, da nadaljujete',
      title: 'Dvostopenjska overjanja',
    },
  },
  signInEnterPasswordTitle: 'Vpišite geslo',
  signUp: {
    alternativePhoneCodeProvider: {
      resendButton: "Nisi prejel kode? Pošlji ponovno",
      subtitle: 'Vpišite kodo, ki je bila poslana na vaš {{provider}}',
      title: 'Preverite svoj {{provider}}',
    },
    continue: {
      actionLink: 'Prijava',
      actionText: 'Že imate račun?',
      subtitle: 'Vpišite preostale področja, da nadaljujete.',
      title: 'Vpišite manjkajoča polja',
    },
    emailCode: {
      formSubtitle: 'Vpišite kodo, ki je bila poslana na vaš e-poštni naslov',
      formTitle: 'Koda za preverjanje',
      resendButton: "Nisi prejel kode? Pošlji ponovno",
      subtitle: 'Vpišite kodo, ki je bila poslana na vaš e-poštni naslov',
      title: 'Preverite svojo e-pošto',
    },
    emailLink: {
      clientMismatch: {
        subtitle:
          'Za nadaljevanje odprite povezavo za preverjanje v napravi in brskalniku, iz katerega ste sprožili prijavo.',
        title: 'Povezava za preverjanje je neveljavna za to napravo',
      },
      formSubtitle: 'Uporabite povezavo za preverjanje, ki je bila poslana na vaš e-poštni naslov',
      formTitle: 'Povezava za preverjanje',
      loading: {
        title: 'Prijavljeni...',
      },
      resendButton: "Nisi prejel povezave? Pošlji ponovno",
      subtitle: 'da nadaljujete do {{applicationName}}',
      title: 'Preverite svojo e-pošto',
      verified: {
        title: 'Prijavljeni',
      },
      verifiedSwitchTab: {
        subtitle: 'Vrnite se na nov odprti zavihek, da nadaljujete.',
        subtitleNewTab: 'Vrnite se na izvirni zavihek, da nadaljujete.',
        title: 'Prijavljeni',
      },
    },
    legalConsent: {
      checkbox: {
        label__onlyPrivacyPolicy: 'Sprejemam {{ privacyPolicyLink || link("Pravilnik o zasebnosti") }}',
        label__onlyTermsOfService: 'Sprejemam {{ termsOfServiceLink || link("Pogoje uporabe") }}',
        label__termsOfServiceAndPrivacyPolicy:
          'Sprejemam {{ termsOfServiceLink || link("Pogoje uporabe") }} in {{ privacyPolicyLink || link("Pravilnik o zasebnosti") }}',
      },
      continue: {
        subtitle: 'Preberite in sprejmite pogoje, da nadaljujete.',
        title: 'Sprejem pogojev',
      },
    },
    phoneCode: {
      formSubtitle: 'Vpišite kodo, ki je bila poslana na vaš telefon',
      formTitle: 'Koda za preverjanje',
      resendButton: "Nisi prejel kode? Pošlji ponovno",
      subtitle: 'Vpišite kodo, ki je bila poslana na vaš telefon',
      title: 'Preverite svoj telefon',
    },
    restrictedAccess: {
      actionLink: 'Prijava',
      actionText: 'Že imate račun?',
      blockButton__emailSupport: 'Pomoč e-pošte',
      blockButton__joinWaitlist: 'Pridruži se seznamu čakanja',
      subtitle: 'Prijave so trenutno onemogočene. Če mislite, da bi imeli dostop, nas prosimo kontaktirajte.',
      subtitleWaitlist: 'Prijave so trenutno onemogočene. Če želite biti prvi, ki bo izvedel, ko začnemo, se pridružite seznamu čakanja.',
      title: 'Dostop onemogočen',
    },
    start: {
      actionLink: 'Prijava',
      actionLink__use_email: 'Uporabi e-pošto namesto telefona',
      actionLink__use_phone: 'Uporabi telefon namesto e-pošte',
      actionText: 'Že imate račun?',
      alternativePhoneCodeProvider: {
        actionLink: 'Uporabi drugo metodo',
        label: '{{provider}} telefonska številka',
        subtitle: 'Vpišite svojo telefonsko številko, da dobite kodo za preverjanje na {{provider}}.',
        title: 'Prijavite se na {{applicationName}} z {{provider}}',
      },
      subtitle: 'Pozdravljeni! Vpišite področja, da nadaljujete.',
      subtitleCombined: 'Pozdravljeni! Vpišite področja, da nadaljujete.',
      title: 'Ustvarite svoj račun',
      titleCombined: 'Ustvarite svoj račun',
    },
  },
  socialButtonsBlockButton: 'Nadaljujte z {{provider|titleize}}',
  socialButtonsBlockButtonManyInView: '{{provider|titleize}}',
  unstable__errors: {
    already_a_member_in_organization: '{{email}} je že član organizacije.',
    captcha_invalid: undefined,
    captcha_unavailable:
      'Prijava ni uspela zaradi neuspešne validacije bot-a. Poskusite ponovno znova ali nas kontaktirajte za več pomoči.',
    form_code_incorrect: undefined,
    form_identifier_exists__email_address: undefined,
    form_identifier_exists__phone_number: undefined,
    form_identifier_exists__username: undefined,
    form_identifier_not_found: undefined,
    form_param_format_invalid: undefined,
    form_param_format_invalid__email_address: undefined,
    form_param_format_invalid__phone_number: undefined,
    form_param_max_length_exceeded__first_name: undefined,
    form_param_max_length_exceeded__last_name: undefined,
    form_param_max_length_exceeded__name: undefined,
    form_param_nil: undefined,
    form_param_type_invalid: undefined,
    form_param_type_invalid__email_address: undefined,
    form_param_type_invalid__phone_number: undefined,
    form_param_value_invalid: undefined,
    form_password_incorrect: undefined,
    form_password_length_too_short: 'Vaše geslo je prekratko. Morate imeti vsaj 8 znakov.',
    form_password_not_strong_enough: 'Vaše geslo ni dovolj močno.',
    form_password_pwned:
      'To geslo je bilo najdeno v ogroženem podatkovnem jezu in se ne more uporabiti, poskusite z drugim geslom namesto tega.',
    form_password_pwned__sign_in:
      'To geslo je bilo najdeno v ogroženem podatkovnem jezu in se ne more uporabiti, ponastavite geslo.',
    form_password_size_in_bytes_exceeded: undefined,
    form_password_validation_failed: undefined,
    form_username_invalid_character: undefined,
    form_username_invalid_length: 'Uporabniško ime mora biti med {{min_length}} in {{max_length}} znaki.',
    identification_deletion_failed: undefined,
    not_allowed_access: undefined,
    organization_domain_blocked: undefined,
    organization_domain_common: undefined,
    organization_domain_exists_for_enterprise_connection: undefined,
    organization_membership_quota_exceeded: undefined,
    organization_minimum_permissions_needed: undefined,
    passkey_already_exists: 'Koda je že registrirana na tej napravi.',
    passkey_not_supported: 'Kode ne podpirajo te naprave.',
    passkey_pa_not_supported: 'Registracija zahteva platformo za overjanje, vendar ta naprava ne podpira tega.',
    passkey_registration_cancelled: 'Registracija kode je bila preklicana ali potekla.',
    passkey_retrieval_cancelled: 'Preverjanje kode je bila preklicana ali potekla.',
    passwordComplexity: {
      maximumLength: 'manj kot {{length}} znakov',
      minimumLength: '{{length}} ali več znakov',
      requireLowercase: 'spodnjo črko',
      requireNumbers: 'številko',
      requireSpecialCharacter: 'posebno črko',
      requireUppercase: 'veliko črko',
      sentencePrefix: 'Vaše geslo mora vsebovati',
    },
    phone_number_exists: undefined,
    session_exists: undefined,
    web3_missing_identifier: 'Web3 Wallet razširitev ni mogoče najti. Namestite jo, da nadaljujete.',
    zxcvbn: {
      couldBeStronger: 'Vaše geslo deluje, vendar bi lahko bilo močnejše. Poskusite dodati več znakov.',
      goodPassword: 'Vaše geslo ustreza vsem potrebnim zahtevam.',
      notEnough: 'Vaše geslo ni dovolj močno.',
      suggestions: {
        allUppercase: 'Zapisite nekatere črke velikimi, vendar ne vse.',
        anotherWord: 'Dodajte več besed, ki so manj pogoste.',
        associatedYears: 'Izpustite leta, ki so povezana z vami.',
        capitalization: 'Zapisite več črk velikimi, vendar ne vse.',
        dates: 'Izpustite datume in leta, ki so povezana z vami.',
        l33t: "Izpustite predvidljive zamenjave črk, kot je '@' namesto 'a'.",
        longerKeyboardPattern: 'Uporabite daljše tipkovniške vzorce in spremenite smer tipkanja večkrat.',
        noNeed: 'Močna gesla lahko ustvarite brez uporabe simbolov, številk ali velikih črk.',
        pwned: 'Če uporabljate to geslo drugje, ga morate spremeniti.',
        recentYears: 'Izpustite nedavna leta.',
        repeated: 'Izpustite ponovljene besede in znake.',
        reverseWords: 'Izpustite obrnjene besede.',
        sequences: 'Izpustite pogoste sekvence znakov.',
        useWords: 'Uporabite več besed, vendar izpustite pogoste fraze.',
      },
      warnings: {
        common: 'To je pogosto uporabljeno geslo.',
        commonNames: 'Pogoste imena in priimki so lahko prepoznavna.',
        dates: 'Datumi so lahko prepoznavni.',
        extendedRepeat: 'Ponovljene sekvence znakov, kot je "abcabcabc", so lahko prepoznavne.',
        keyPattern: 'Kratke tipkovniške sekvence so lahko prepoznavne.',
        namesByThemselves: 'Pogoste imena in priimki so lahko prepoznavna.',
        pwned: 'Vaše geslo je bilo izpostavljeno v ogroženem podatkovnem jezu na internetu.',
        recentYears: 'Nedavna leta so lahko prepoznavna.',
        sequences: 'Pogoste sekvence znakov, kot je "abc", so lahko prepoznavne.',
        similarToCommon: 'To je podobno pogostemu geslu.',
        simpleRepeat: 'Ponovljeni znaki, kot je "aaa", so lahko prepoznavni.',
        straightRow: 'Pogoste sekvence tipkovnice so lahko prepoznavne.',
        topHundred: 'To je pogosto uporabljeno geslo.',
        topTen: 'To je pogosto uporabljeno geslo.',
        userInputs: 'Na geslu ne bi smelo biti nobenih osebnih ali stranih podatkov.',
        wordByItself: 'Pogoste besede so lahko prepoznavne.',
      },
    },
  },
  userButton: {
    action__addAccount: 'Dodaj račun',
    action__manageAccount: 'Upravljaj račun',
    action__signOut: 'Odjava',
    action__signOutAll: 'Odjava iz vseh računov',
  },
  userProfile: {
    apiKeysPage: {
      title: 'API ključi',
    },
    backupCodePage: {
      actionLabel__copied: 'Copied!',
      actionLabel__copy: 'Copy all',
      actionLabel__download: 'Download .txt',
      actionLabel__print: 'Print',
      infoText1: 'Backup codes will be enabled for this account.',
      infoText2:
        'Shranite kopije in ohranite jih v skladu z zasebnostjo. Če ste skeptični, da so kopije kompromitirane, jih lahko ponovno ustvarite.',
      subtitle__codelist: 'Shranite jih v skladu z zasebnostjo in ohranite jih skrivno.',
      successMessage:
        'Kopije so zdaj omogočene. Uporabite jih za prijavo na svoj račun, če izgubite dostop do overilne naprave. Vsaka kopija lahko uporabite samo enkrat.',
      successSubtitle:
        'Uporabite jih za prijavo na svoj račun, če izgubite dostop do overilne naprave.',
      title: 'Dodajte preverjanje kopije',
      title__codelist: 'Kopije',
    },
    billingPage: {
      paymentHistorySection: {
        empty: 'No payment history',
        notFound: 'Plačilni poskus ni najden',
        tableHeader__amount: 'Znesek',
        tableHeader__date: 'Datum',
        tableHeader__status: 'Status',
      },
      paymentSourcesSection: {
        actionLabel__default: 'Nastavi kot privzeto',
        actionLabel__remove: 'Odstrani',
        add: 'Dodaj novo plačilno metodo',
        addSubtitle: 'Dodajte novo plačilno metodo na svoj račun.',
        cancelButton: 'Prekliči',
        formButtonPrimary__add: 'Dodaj plačilno metodo',
        formButtonPrimary__pay: 'Plačaj {{amount}}',
        payWithTestCardButton: 'Plačaj z testno kartico',
        removeResource: {
          messageLine1: '{{identifier}} bo odstranjen iz tega računa.',
          messageLine2:
            'Ne boste več mogli uporabljati te plačilne metode in bodo vsi ponavljajoči se naročini, odvisni od nje, več ne delovali.',
          successMessage: '{{paymentSource}} je bil odstranjen iz vašega računa.',
          title: 'Odstrani plačilno metodo',
        },
        title: 'Plačilne metode',
      },
      start: {
        headerTitle__payments: 'Plačila',
        headerTitle__plans: 'Načini',
        headerTitle__statements: 'Izjave',
        headerTitle__subscriptions: 'Naročnina',
      },
      statementsSection: {
        empty: 'Ni izjav za prikaz',
        itemCaption__paidForPlan: 'Plačano za {{plan}} {{period}} način',
        itemCaption__proratedCredit: 'Proratirana kreditna vrednost za delno uporabo prejšnjega naročnina',
        itemCaption__subscribedAndPaidForPlan: 'Naročen in plačan za {{plan}} {{period}} način',
        notFound: 'Izjava ni najdena',
        tableHeader__amount: 'Znesek',
        tableHeader__date: 'Datum',
        title: 'Izjave',
        totalPaid: 'Skupaj plačano',
      },
      subscriptionsListSection: {
        actionLabel__newSubscription: 'Naroči se na način',
        actionLabel__switchPlan: 'Spremeni način',
        tableHeader__edit: 'Uredi',
        tableHeader__plan: 'Način',
        tableHeader__startDate: 'Datum začetka',
        title: 'Naročnina',
      },
      subscriptionsSection: {
        actionLabel__default: 'Upravljaj',
      },
      switchPlansSection: {
        title: 'Spremeni način',
      },
      title: 'Računovodstvo',
    },
    connectedAccountPage: {
      formHint: 'Izberite ponudnika, da povežete svoj račun.',
      formHint__noAccounts: 'Ni na voljo nobenih zunanjih ponudnikov računov.',
      removeResource: {
        messageLine1: '{{identifier}} bo odstranjen iz tega računa.',
        messageLine2:
          'Ne boste več mogli uporabljati te povezane račune in bodo vsi odvisni funkcije več ne delovali.',
        successMessage: '{{connectedAccount}} je bil odstranjen iz vašega računa.',
        title: 'Odstrani povezan račun',
      },
      socialButtonsBlockButton: '{{provider|titleize}}',
      successMessage: 'Ponudnik je bil dodan na vaš račun',
      title: 'Dodaj povezan račun',
    },
    deletePage: {
      actionDescription: 'Vpišite "Izbriši račun" spodaj, da nadaljujete.',
      confirm: 'Izbriši račun',
      messageLine1: 'Ste prepričani, da želite izbrisati svoj račun?',
      messageLine2: 'To dejanje je trajno in nepovratno.',
      title: 'Delete account',
    },
    emailAddressPage: {
      emailCode: {
        formHint: 'E-pošta z kodo za preverjanje bo poslana na to e-pošto.',
        formSubtitle: 'Vpišite kodo za preverjanje, poslan na {{identifier}}',
        formTitle: 'Koda za preverjanje',
        resendButton: "Niste prejeli kode? Pošlji ponovno",
        successMessage: 'E-pošta {{identifier}} je bila dodana na vaš račun.',
      },
      emailLink: {
        formHint: 'E-pošta z povezavo za preverjanje bo poslana na to e-pošto.',
        formSubtitle: 'Kliknite na povezavo za preverjanje v e-pošti, poslan na {{identifier}}',
        formTitle: 'Povezava za preverjanje',
        resendButton: "Niste prejeli povezave? Pošlji ponovno",
        successMessage: 'E-pošta {{identifier}} je bila dodana na vaš račun.',
      },
      enterpriseSSOLink: {
        formButton: 'Kliknite za prijavo',
        formSubtitle: 'Dokončajte prijavo z {{identifier}}',
      },
      formHint: "Preden lahko dodate to e-pošto na svoj račun, jo morate preveriti.",
      removeResource: {
        messageLine1: '{{identifier}} bo odstranjen iz tega računa.',
        messageLine2: 'Ne boste več mogli prijaviti z uporabo te e-pošte.',
        successMessage: '{{emailAddress}} je bil odstranjen iz vašega računa.',
        title: 'Odstrani e-pošto',
      },
      title: 'Dodaj e-pošto',
      verifyTitle: 'Preveri e-pošto',
    },
    formButtonPrimary__add: 'Dodaj',
    formButtonPrimary__continue: 'Nadaljuj',
    formButtonPrimary__finish: 'Končaj',
    formButtonPrimary__remove: 'Odstrani',
    formButtonPrimary__save: 'Shrani',
    formButtonReset: 'Prekliči',
    mfaPage: {
      formHint: 'Izberite metodo za dodajanje.',
      title: 'Dodaj dvo-korakovno preverjanje',
    },
    mfaPhoneCodePage: {
      backButton: 'Use existing number',
      primaryButton__addPhoneNumber: 'Add phone number',
      removeResource: {
        messageLine1: '{{identifier}} ne bo več prejemal kod za preverjanje pri prijavi.',
        messageLine2: 'Vaš račun morda ni tako varn. Ste prepričani, da želite nadaljevati?',
        successMessage: 'SMS koda dvo-korakovnega preverjanja je bila odstranjena za {{mfaPhoneCode}}',
        title: 'Odstrani dvo-korakovno preverjanje',
      },
      subtitle__availablePhoneNumbers:
        'Izberite obstoječi telefonski številk, da se registrirate za SMS kodo dvo-korakovnega preverjanja, ali dodajte novo.',
      subtitle__unavailablePhoneNumbers:
        'Ni na voljo nobenih telefonskih številk za registracijo SMS kode dvo-korakovnega preverjanja, dodajte novo.',
      successMessage1:
        'Pri prijavi boste morali vnesti kodo za preverjanje, poslan na to telefonsko številko, kot dodaten korak.',
      successMessage2:
        'Shranite te kopije in shranite jih nekam varno. Če izgubite dostop do overilne naprave, lahko uporabite kopije za prijavo.',
      successTitle: 'SMS koda preverjanja omogočena',
      title: 'Dodaj SMS kodo preverjanja',
    },
    mfaTOTPPage: {
      authenticatorApp: {
        buttonAbleToScan__nonPrimary: 'Skeniraj QR kodo namesto tega',
        buttonUnableToScan__nonPrimary: 'Ne moreš skenirati QR kode?',
        infoText__ableToScan:
          'Set up a new sign-in method in your authenticator app and scan the following QR code to link it to your account.',
        infoText__unableToScan: 'Set up a new sign-in method in your authenticator and enter the Key provided below.',
        inputLabel__unableToScan1:
          'Preverite, ali je omogočeno časovno ali enkratno geslo, nato končajte povezovanje svojega računa.',
        inputLabel__unableToScan2:
          'Alternativno, če vaš overilnik podpira TOTP URI, lahko tudi kopirate celoten URI.',
      },
      removeResource: {
        messageLine1: 'Kode za preverjanje iz tega overilnika ne bodo več potrebne pri prijavi.',
        messageLine2: 'Vaš račun morda ni tako varn. Ste prepričani, da želite nadaljevati?',
        successMessage: 'Dvo-korakovno preverjanje preko overilnika je bilo odstranjeno.',
        title: 'Odstrani dvo-korakovno preverjanje',
      },
      successMessage:
        'Dvo-korakovno preverjanje je zdaj omogočeno. Pri prijavi boste morali vnesti kodo za preverjanje iz tega overilnika kot dodaten korak.',
      title: 'Dodaj overilnik',
      verifySubtitle: 'Vpišite kodo za preverjanje, generirano z vašim overilnikom',
      verifyTitle: 'Koda za preverjanje',
    },
    mobileButton__menu: 'Meni',
    navbar: {
      account: 'Profil',
      apiKeys: 'API ključi',
      billing: 'Računovodstvo',
      description: 'Upravljajte svoje podatke računa.',
      security: 'Varnost',
      title: 'Račun',
    },
    passkeyScreen: {
      removeResource: {
        messageLine1: '{{name}} bo odstranjen iz tega računa.',
        title: 'Odstrani kodo',
      },
      subtitle__rename: 'Kodo lahko preimenujete, da bo lažje najti.',
      title__rename: 'Preimenuj kodo',
    },
    passwordPage: {
      checkboxInfoText__signOutOfOtherSessions:
        'Priporočljivo je odjaviti vse druge naprave, ki so lahko uporabile vaše stare geslo.',
      readonly: 'Vaše geslo trenutno ni mogoče urejati, ker lahko prijavite le prek podjetnega povezave.',
      successMessage__set: 'Vaše geslo je bilo nastavljeno.',
      successMessage__signOutOfOtherSessions: 'Vse druge naprave so bile odjavljene.',
      successMessage__update: 'Vaše geslo je bilo posodobljeno.',
      title__set: 'Nastavi geslo',
      title__update: 'Posodobi geslo',
    },
    phoneNumberPage: {
      infoText:
        'Sms koda za preverjanje bo poslana na to telefonsko številko. Mogoče bodo obračunani stroški.',
      removeResource: {
        messageLine1: '{{identifier}} bo odstranjen iz tega računa.',
        messageLine2: 'Ne boste več mogli prijaviti z uporabo te telefonske številke.',
        successMessage: '{{phoneNumber}} je bil odstranjen iz vašega računa.',
        title: 'Odstrani telefonsko številko',
      },
      successMessage: '{{identifier}} je bila dodana na vaš račun.',
      title: 'Dodaj telefonsko številko',
      verifySubtitle: 'Vpišite kodo za preverjanje, poslan na {{identifier}}',
      verifyTitle: 'Preveri telefonsko številko',
    },
    plansPage: {
      title: 'Načini',
    },
    profilePage: {
      fileDropAreaHint: 'Priporočljivo velikost 1:1, do 10MB.',
      imageFormDestructiveActionSubtitle: 'Odstrani',
      imageFormSubtitle: 'Naloži',
      imageFormTitle: 'Slika profila',
      readonly: 'Vaše podatke profila je poslal podjetni povezave in jih ni mogoče urejati.',
      successMessage: 'Vaš profil je bil posodobljen.',
      title: 'Posodobi profil',
    },
    start: {
      activeDevicesSection: {
        destructiveAction: 'Odjavi napravo',
        title: 'Aktivne naprave',
      },
      connectedAccountsSection: {
        actionLabel__connectionFailed: 'Poveži ponovno',
        actionLabel__reauthorize: 'Avtoriziraj zdaj',
        destructiveActionTitle: 'Odstrani',
        primaryButton: 'Poveži račun',
        subtitle__disconnected: 'Ta račun je bil odstranjen.',
        subtitle__reauthorize:
          'Zahtevani obsegi so bili posodobljeni, in morda boste imeli omejene funkcionalnosti. Prosimo, avtorizirajte aplikacijo, da se izognete težavam',
        title: 'Povezani računi',
      },
      dangerSection: {
        deleteAccountButton: 'Izbriši račun',
        title: 'Izbriši račun',
      },
      emailAddressesSection: {
        destructiveAction: 'Odstrani e-pošto',
        detailsAction__nonPrimary: 'Nastavi kot primarno',
        detailsAction__primary: 'Dokončaj preverjanje',
        detailsAction__unverified: 'Preveri',
        primaryButton: 'Dodaj e-pošto',
        title: 'E-pošte',
      },
      enterpriseAccountsSection: {
        title: 'Podjetni računi',
      },
      headerTitle__account: 'Podrobnosti profila',
      headerTitle__security: 'Varnost',
      mfaSection: {
        backupCodes: {
          actionLabel__regenerate: 'Regeneriraj',
          headerTitle: 'Kopije',
          subtitle__regenerate:
            'Dobite novo varno kopijo. Predhodne kopije bodo odstranjene in ne bodo mogle biti uporabljene.',
          title__regenerate: 'Regeneriraj kopije',
        },
        phoneCode: {
          actionLabel__setDefault: 'Nastavi kot privzeto',
          destructiveActionLabel: 'Odstrani',
        },
        primaryButton: 'Dodaj dvo-korakovno preverjanje',
        title: 'Dvo-korakovno preverjanje',
        totp: {
          destructiveActionTitle: 'Odstrani',
          headerTitle: 'Overilnik',
        },
      },
      passkeysSection: {
        menuAction__destructive: 'Odstrani',
        menuAction__rename: 'Preimenuj',
        primaryButton: 'Dodaj kodo',
        title: 'Kode',
      },
      passwordSection: {
        primaryButton__setPassword: 'Nastavi geslo',
        primaryButton__updatePassword: 'Posodobi geslo',
        title: 'Geslo',
      },
      phoneNumbersSection: {
        destructiveAction: 'Odstrani telefonsko številko',
        detailsAction__nonPrimary: 'Nastavi kot primarno',
        detailsAction__primary: 'Dokončaj preverjanje',
        detailsAction__unverified: 'Preveri telefonsko številko',
        primaryButton: 'Dodaj telefonsko številko',
        title: 'Telefonske številke',
      },
      profileSection: {
        primaryButton: 'Posodobi profil',
        title: 'Profil',
      },
      usernameSection: {
        primaryButton__setUsername: 'Nastavi uporabniško ime',
        primaryButton__updateUsername: 'Posodobi uporabniško ime',
        title: 'Uporabniško ime',
      },
      web3WalletsSection: {
        destructiveAction: 'Odstrani denarnico',
        detailsAction__nonPrimary: 'Nastavi kot primarno',
        primaryButton: 'Poveži denarnico',
        title: 'Denarnice',
      },
    },
    usernamePage: {
      successMessage: 'Vaše uporabniško ime je bilo posodobljeno.',
      title__set: 'Nastavi uporabniško ime',
      title__update: 'Posodobi uporabniško ime',
    },
    web3WalletPage: {
      removeResource: {
        messageLine1: '{{identifier}} bo odstranjen iz tega računa.',
        messageLine2: 'Ne boste več mogli prijaviti z uporabo te denarnice.',
        successMessage: '{{web3Wallet}} je bil odstranjen iz vašega računa.',
        title: 'Odstrani denarnico',
      },
      subtitle__availableWallets: 'Izberite denarnico, da se povežete z vašim računom.',
      subtitle__unavailableWallets: 'Ni na voljo nobenih denarnic.',
      successMessage: 'Denarnica je bila dodana na vaš račun.',
      title: 'Dodaj denarnico',
      web3WalletButtonsBlockButton: '{{provider|titleize}}', // TODO: Check if this is correct
    },
  },
  waitlist: {
    start: {
      actionLink: 'Prijavi se',
      actionText: 'Že imate dostop?',
      formButton: 'Pridruži se seznamu čakanja',
      subtitle: 'Vpišite svojo e-pošto in bomo vam poslali e-pošto, ko bo vaše mesto pripravljeno',
      title: 'Pridruži se seznamu čakanja',
    },
    success: {
      message: 'Boste preusmerjeni čez nekaj sekund...',
      subtitle: 'Bomo vam poslali e-pošto, ko bo vaše mesto pripravljeno',
      title: 'Hvala, da ste se pridružili seznamu čakanja!',
    },
  },
} as const;